### ISSUE TITLE
NOCACHE not working with redis 5.0.3 

### ISSUE THREAD

**Issue by matth-c3** [RedisLabsModules/redisjson#108]
Hello, 

Everything is in the title : 

```
redis_1  | 1:M 26 Feb 2019 23:15:59.188 # <ReJSON> Unknown option NOCACHE
redis_1  | 1:M 26 Feb 2019 23:15:59.188 # Module /tmp/rejson.so initialization failed. Module not loaded
redis_1  | 1:M 26 Feb 2019 23:15:59.188 # Can't load module from /tmp/rejson.so: server aborting
```

Module was built from the docker image redis 5.0.3 using the following command : 

bash -c "apt-get update && apt-get install -y git build-essential && rm -rf redisjson && git clone https://github.com/RedisLabsModules/redisjson.git && cd redisjson/ && make && mv src/rejson.so /tmp && redis-server --requirepass pwdRedisTest --loadmodule /tmp/rejson.so NOCACHE"

Thanks.

**Comment by mnunberg** [comment]
The option was changed from `NOCACHE` to `CACHE OFF`. It's also disabled by default, too.
